// Generated by CoffeeScript 1.4.0
(function() {
  var pouchdb, slice;

  pouchdb = angular.module('pouchdb', ['ng']);

  slice = Array.prototype.slice;

  pouchdb.provider('pouchdb', function() {
    return {
      withAllDbsEnabled: function() {
        return PouchDB.enableAllDbs = true;
      },
      $get: function($q, $rootScope) {
        var qify;
        qify = function(fn) {
          return function() {
            var args, callback, deferred;
            deferred = $q.defer();
            callback = function(err, res) {
              return $rootScope.$apply(function() {
                if (err) {
                  return deferred.reject(err);
                } else {
                  return deferred.resolve(res);
                }
              });
            };
            args = arguments != null ? slice.call(arguments) : [];
            args.push(callback);
            fn.apply(this, args);
            return deferred.promise;
          };
        };
        return {
          create: function(name, options) {
            var db;
            db = new PouchDB(name, options);
            return {
              put: qify(db.put),
              post: qify(db.post),
              get: qify(db.get),
              remove: qify(db.remove),
              bulkDocs: qify(db.bulkDocs),
              allDocs: qify(db.allDocs),
              changes: function(options) {
                var clone;
                clone = angular.copy(options);
                clone.onChange = function(change) {
                  return $rootScope.$apply(function() {
                    return options.onChange(change);
                  });
                };
                return db.changes(clone);
              },
              putAttachment: qify(db.putAttachment),
              getAttachment: qify(db.getAttachment),
              removeAttachment: qify(db.removeAttachment),
              query: qify(db.query),
              info: qify(db.info),
              compact: qify(db.compact),
              revsDiff: qify(db.revsDiff)
            };
          },
          allDbs: qify(PouchDB.allDbs),
          destroy: qify(PouchDB.destroy),
          replicate: PouchDB.replicate
        };
      }
    };
  });

  pouchdb.directive('pouchRepeat', function() {
    return {
      transclude: 'element',
      compile: function(elem, attrs, transclude) {
        return function($scope, $element, $attr) {
          var blocks, collection, cursor, parent, _ref;
          parent = $element.parent();
          _ref = /^\s*([a-zA-Z0-9]+)\s*in\s*([a-zA-Z0-9]+)\s*$/.exec($attr.pouchRepeat).splice(1), cursor = _ref[0], collection = _ref[1];
          blocks = {};
          return $scope.$watch(collection, function() {
            var displayAll, displayDoc;
            displayDoc = function(doc) {
              var childScope;
              childScope = $scope.$new();
              childScope[cursor] = doc;
              return transclude(childScope, function(clone) {
                blocks[doc._id] = {
                  clone: clone,
                  scope: childScope
                };
                return parent.append(clone);
              });
            };
            displayAll = function(docs) {
              var row, _i, _len, _ref1, _results;
              _ref1 = docs.rows;
              _results = [];
              for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                row = _ref1[_i];
                _results.push(displayDoc(row.doc));
              }
              return _results;
            };
            $scope[collection].allDocs({
              include_docs: true
            }).then(displayAll);
            $scope[collection].info().then(function(info) {
              return $scope[collection].changes({
                include_docs: true,
                continuous: true,
                since: info.update_seq,
                onChange: function(update) {
                  var block;
                  block = blocks[update.id];
                  if (update.deleted) {
                    block.clone.remove();
                    return block.scope.$destroy();
                  } else {
                    if (block != null) {
                      return block.scope[cursor] = update.doc;
                    } else {
                      return displayDoc(update.doc);
                    }
                  }
                }
              });
            });
          });
        };
      }
    };
  });

}).call(this);
